### ISSUE TITLE
getcoords: command not found

### ISSUE THREAD

**Issue by juddfranklin1** [melanieseltzer/getcoords-cli#1]
Thanks for the helpful tool!

I installed the CLI locally to a directory, rather than globally, and was able to successfully get geocoordinates by running `node cli.js ADDRESS`. However, running `getcoords --help` returns `getcoords: command not found`.

**Comment by melanieseltzer** [comment]
Hi! You're welcome!

So, `getcoords-cli` is intended to be installed globally rather than locally, which is why the command isn't recognized in your local install.

It makes use of the `bin` field in package.json to symlink the executable (`lib/cli.js`) to /usr/local/bin/getcoords (basically, it's a map of the command name `getcoords` to local file name `lib/cli`). 

That enables the cli command `getcoords` to be executed anywhere, not just constrained to one project folder. More info [here](https://docs.npmjs.com/files/package.json#bin).

**Comment by melanieseltzer** [comment]
Actually! You can in fact execute the commands locally if you want, with the handy `npx` 😄 It is shipped with npm by default from v@5.2.0, but if you don't have it already just run:

`npm install -g npx`

Then in your local project directory, you can now run:

`npx getcoords "..."`

Let me know if that fixes the issue. I'll pop that info into the readme as well.

**Comment by juddfranklin1** [comment]
Seems like a cool idea, but it doesn't seem to be working. Here's what I get.

```
$ npx getcoords
npx: installed 6 in 3.216s
command not found: getcoords
$ node -v
v10.5.0
```
The reason I don't want to install this globally is that if I ship it with a project as a dependency, I can't depend upon an end user installing it globally.

I have a workaround, though. According to [this](http://stackoverflow.com/questions/14657170/ddg#14657796), I can define simple commands like this as package.json scripts, so I can then execute `npm run getcoords`. I will add it and submit a pull request. Thanks!

**Comment by melanieseltzer** [comment]
Hm. I think I'm sensing some misunderstanding about what this cli is, and its usecase. 

`getcoords-cli` is a wrapper of sorts around the [getcoords](https://github.com/melanieseltzer/getcoords) function (which is just a regular async function that you could use anywhere). They're separate modules. `getcoords-cli` imports [getcoords](https://github.com/melanieseltzer/getcoords) as a dependency and enables you to execute it anywhere on your system, via the terminal, as a Node cli app.

`getcoords-cli` cannot be required in a project as a dependency in the sense that you won't be able to do something like `const getcoords-cli = require('getcoords-cli')` in your code. So, you shouldn't be adding it to your package.json. If you did want to use the underlying functionality in your app, you would install [getcoords](https://github.com/melanieseltzer/getcoords) as a dependency, not the cli.

**Comment by melanieseltzer** [comment]
D'oh. I'm an idiot. I was misunderstanding you. Yeah, if you need ship `getcoords-cli` along with your project for some reason (to allow others access to the cli without having to install it globally themselves? Though I would question why they wouldn't just install the global cli because that's easier...), you can `npm install` it as a dependency and use the script key in your package.json:

```
"scripts": {
  "getcoords": "./node_modules/.bin/getcoords"
}
```

`npm run getcoords '...'` will then work.

**Comment by juddfranklin1** [comment]
Thanks.

**Comment by juddfranklin1** [comment]
You're good. I was getting out ahead of myself. I didn't really think through the functionality I had in mind, vs what you are going for here.

I envision this as part of a more elaborate CLI like a website generator using this and some of the other Google Maps APIs to generate maps and pages with embedded maps. But that's a totally different project.

I wish I had had this tool at Still Water.
